### PR TITLE
RPS By Amy

### PR DESCRIPTION
**Pull request by amymariewall**

### CODE REVIEW

**Comment by amymariewall** [comment]
I am about to start writing tests for my algorithmic methods and then attempting to refactor into classes. I want to check first that I have sufficiently refactored my methods to begin the next steps.

**Comment by amymariewall** [comment]
I created an OOP version. The four files in the lib directory are now: 
- Functional Programming Methods (method_file.rb)
- Functional Programming RPS program (rock_paper_scissors.rb)
- OOP Class and Methods (RPS_OOP_Method_File.rb)
- OOP RPS Program (RPS_OOP.rb)

I am now planning to create some tests for the OOP version.

**Comment by amymariewall** [comment]
The Google questionnaire this morning got me wondering how to answer the question about whether 'global' variables are in use in my program. In the "functional programming" approach, I used the @ symbol in front of some variables and it seemed to make them work like global variables. So...I suppose my answer to that question is yes, I am using global variables? The functional programming approach methods are in lib/method_file.rb and the functional program itself is in lib/rock_paper_scissors.rb, and they are running as I expect them to.

**Comment by amymariewall** [comment]
Would this be considered ready to move on? I have an OOP version running with tests passing. The four files that are relevant are:

**OOP**:

RPS_OOP_Method_File.rb
RPS_OOP.rb

**Functional Approach**:

method_file.rb
rock_paper_scissors.rb

**Comment by sumeetjain** [comment]
:+1:

**Comment by amymariewall** [comment]
:smile: Thanks! I am still curious about the global variables in my Functional Programming approach if you ever get a chance to take a look at that question (in a comment above). The file to refer to is method_file.rb - it contains the methods for my "Functional Programming" driver program, rock_paper_scissors.rb.

**Comment by sumeetjain** [comment]
> The Google questionnaire this morning got me wondering how to answer the question about whether 'global' variables are in use in my program. In the "functional programming" approach, I used the @ symbol in front of some variables and it seemed to make them work like global variables. So...I suppose my answer to that question is yes, I am using global variables? The functional programming approach methods are in lib/method_file.rb and the functional program itself is in lib/rock_paper_scissors.rb, and they are running as I expect them to.

Right. So you are using global variables, and your approach is not a _pure_ FP approach. Take this method for example:

``` ruby
def add_win_to_score(winner)
  if winner == 1
    @player_1_score += 1
  elsif winner == 2
    @player_2_score += 1
  end
end
```

A true FP approach would be more like this:

First, set non-global, just plain ol' local variables for the score tallies. This would be done outside of any method. You'd just have them hanging out in the file where you call methods. So let's say you have:

``` ruby
player1_score = 0
player2_score = 0
```

Then your method would be something like this:

``` ruby
def add_win_to_score(p1score, p2score, winner)
  if winner == 1
    return p1score + 1
  elsif winner == 2
    return p2score + 1
  end
end
```

The goal of this method is to return the new value of the relevant score tally. And wherever you _called_ this method, you would capture its output:

``` ruby
new_score_value = add_win_to_score(p1score, p2score, winner)
```

And then you'd use that captured output to modify the relevant score tally:

``` ruby
player1_score = new_score_value
```

This is the "handing-of-the-baton" style of FP. Each method, if it changes a value, needs to return that value. Then we capture that value and update our variables as needed.

**Pull request closed without merging**
